name: Pipeline simple de ejemplo

on: [push]

jobs:
  saludo:
    runs-on: macos-latest
    steps:
      - run: echo "este es un job de ejemplo en GitHub"
      - run: echo "finalizando job"
  despedida:
    runs-on: macos-latest
    steps:
      - run: echo "cerrando"